// flow-typed signature: c5e2570426211d29b0cfe132b358cb54
// flow-typed version: <<STUB>>/highlights_v^2.1.3/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'highlights'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'highlights' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'highlights/lib/cli' {
  declare module.exports: any;
}

declare module 'highlights/lib/highlights' {
  declare module.exports: any;
}

// Filename aliases
declare module 'highlights/lib/cli.js' {
  declare module.exports: $Exports<'highlights/lib/cli'>;
}
declare module 'highlights/lib/highlights.js' {
  declare module.exports: $Exports<'highlights/lib/highlights'>;
}
