// flow-typed signature: 2594875f1c24d96846fa825decf56db9
// flow-typed version: <<STUB>>/jison-loader_v^1.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jison-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jison-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jison-loader/index' {
  declare module.exports: $Exports<'jison-loader'>;
}
declare module 'jison-loader/index.js' {
  declare module.exports: $Exports<'jison-loader'>;
}
